#!/usr/bin/env bash
# install_agent_linux.sh
#
# Automated installer for bench-race agent on Linux
# - Auto-detects system specs (CPU, RAM, GPU)
# - Generates minimal agent.yaml with user input
# - Sets up Python venv and installs dependencies
# - Runs smoke tests (/health, /capabilities)
#
# Usage:
#   ./install_agent_linux.sh [--agent-id ID] [--label "Label"] [--central-url URL]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
AGENT_DIR="${REPO_ROOT}/agent"
CONFIG_DIR="${AGENT_DIR}/config"
CONFIG_FILE="${CONFIG_DIR}/agent.yaml"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# ============================================================================
# Helper Functions
# ============================================================================

log_info() {
    echo -e "${BLUE}[INFO]${NC} $*"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $*"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $*"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $*"
}

# Sanitize hostname for use as machine_id
sanitize_id() {
    local input="$1"
    echo "$input" | tr '[:upper:]' '[:lower:]' | tr -c '[:alnum:]-' '-' | sed 's/^-//;s/-$//'
}

# Best-effort command execution with timeout
run_with_timeout() {
    local timeout_seconds="$1"
    shift
    timeout "${timeout_seconds}" "$@" 2>/dev/null || true
}

# ============================================================================
# System Detection Functions
# ============================================================================

detect_hostname() {
    hostname -s 2>/dev/null || hostname 2>/dev/null || echo "unknown-host"
}

detect_cpu_cores() {
    nproc 2>/dev/null || echo "unknown"
}

detect_cpu_name() {
    local cpu_name
    cpu_name=$(run_with_timeout 1 lscpu | grep "Model name" | sed 's/Model name:[[:space:]]*//' | head -1)
    if [[ -z "$cpu_name" ]]; then
        cpu_name=$(run_with_timeout 1 grep "model name" /proc/cpuinfo | head -1 | sed 's/.*: //')
    fi
    echo "${cpu_name:-Unknown CPU}"
}

detect_ram_gb() {
    local ram_bytes
    ram_bytes=$(run_with_timeout 1 free -b | awk '/^Mem:/ {print $2}')
    if [[ -n "$ram_bytes" && "$ram_bytes" != "0" ]]; then
        echo $((ram_bytes / 1024 / 1024 / 1024))
    else
        echo "unknown"
    fi
}

detect_gpu_info() {
    local gpu_name=""
    local gpu_vram_gb=""

    # Try nvidia-smi first
    if command -v nvidia-smi &>/dev/null; then
        local gpu_data
        gpu_data=$(run_with_timeout 2 nvidia-smi --query-gpu=name,memory.total --format=csv,noheader 2>/dev/null | head -1)
        if [[ -n "$gpu_data" ]]; then
            gpu_name=$(echo "$gpu_data" | cut -d',' -f1 | xargs)
            local vram_mib=$(echo "$gpu_data" | cut -d',' -f2 | sed 's/[^0-9]//g')
            if [[ -n "$vram_mib" ]]; then
                gpu_vram_gb=$((vram_mib / 1024))
            fi
        fi
    fi

    # Try lspci as fallback
    if [[ -z "$gpu_name" ]] && command -v lspci &>/dev/null; then
        gpu_name=$(run_with_timeout 1 lspci | grep -i "VGA\|3D\|Display" | head -1 | sed 's/.*: //' || echo "")
    fi

    if [[ -z "$gpu_name" ]]; then
        echo "CPU-only"
    elif [[ -n "$gpu_vram_gb" ]]; then
        echo "${gpu_name} (${gpu_vram_gb}GB VRAM)"
    else
        echo "${gpu_name}"
    fi
}

# ============================================================================
# User Input Functions
# ============================================================================

prompt_for_agent_id() {
    local default_id="$1"
    local agent_id

    echo "" >&2
    log_info "Enter a unique machine ID for this agent" >&2
    log_info "This ID must match the machine_id in central/config/machines.yaml" >&2
    read -rp "Machine ID [${default_id}]: " agent_id </dev/tty
    agent_id="${agent_id:-${default_id}}"
    sanitize_id "$agent_id"
}

prompt_for_label() {
    local default_label="$1"
    local label

    echo "" >&2
    log_info "Enter a human-friendly label for this machine" >&2
    log_info "This label will be displayed in the UI" >&2
    read -rp "Label [${default_label}]: " label </dev/tty
    echo "${label:-${default_label}}"
}

prompt_for_central_url() {
    local default_url="http://127.0.0.1:8080"
    local url

    echo "" >&2
    log_info "Enter the URL of the central server" >&2
    read -rp "Central URL [${default_url}]: " url </dev/tty
    echo "${url:-${default_url}}"
}

# ============================================================================
# Configuration Generation
# ============================================================================

generate_agent_yaml() {
    local machine_id="$1"
    local label="$2"
    local central_url="$3"

    log_info "Generating agent.yaml..."

    cat > "$CONFIG_FILE" <<EOF
# agent/config/agent.yaml
#
# Auto-generated by install_agent_linux.sh
# Generated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")

# ============================================================================
# REQUIRED FIELDS
# ============================================================================

machine_id: "${machine_id}"
label: "${label}"

# ============================================================================
# NETWORK CONFIGURATION
# ============================================================================

bind_host: "0.0.0.0"
bind_port: 9001

ollama_base_url: "http://127.0.0.1:11434"
central_base_url: "${central_url}"

# ============================================================================
# OPTIONAL CONFIGURATION
# ============================================================================

comfyui:
  enabled: true
  host: "127.0.0.1"
  port: 8188
  checkpoints_dir: "/opt/comfyui/models/checkpoints"
  install_dir: "/opt/comfyui"
  allow_cpu_fallback: false

runtime_sampler:
  enabled: true
  interval_s: 1
  buffer_len: 120
EOF

    log_success "Generated ${CONFIG_FILE}"
}

# ============================================================================
# Installation Functions
# ============================================================================

setup_python_venv() {
    log_info "Setting up Python virtual environment..."

    # Check Python version
    local python_version
    python_version=$(python3 --version 2>&1 | awk '{print $2}')
    local major_minor
    major_minor=$(echo "$python_version" | cut -d. -f1,2)

    log_info "Detected Python version: ${python_version}"

    # Warn if Python 3.14+ (too new, may have compatibility issues)
    if [[ "${major_minor}" == "3.14" ]] || [[ "${major_minor}" > "3.14" ]]; then
        log_warning "Python ${python_version} detected - this version is very new and may have compatibility issues"
        log_warning "Recommended: Python 3.11, 3.12, or 3.13"
        log_warning "If you encounter errors, try using an older Python version:"
        log_warning "  python3.12 -m venv ${AGENT_DIR}/.venv"
        echo ""
        read -rp "Continue anyway? (y/N): " -n 1 -r </dev/tty
        echo ""
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            log_error "Installation aborted by user"
            return 1
        fi
    fi

    if [[ ! -d "${AGENT_DIR}/.venv" ]]; then
        python3 -m venv "${AGENT_DIR}/.venv"
        log_success "Created Python venv at ${AGENT_DIR}/.venv"
    else
        log_info "Python venv already exists"
    fi

    # shellcheck disable=SC1091
    source "${AGENT_DIR}/.venv/bin/activate"

    log_info "Installing Python dependencies..."
    pip install --quiet --upgrade pip
    pip install --quiet -r "${AGENT_DIR}/requirements.txt" || {
        log_error "Failed to install Python dependencies"
        log_error "If using Python 3.14+, try removing the venv and using Python 3.12:"
        log_error "  rm -rf ${AGENT_DIR}/.venv"
        log_error "  python3.12 -m venv ${AGENT_DIR}/.venv"
        return 1
    }

    log_success "Python dependencies installed"
}

# ============================================================================
# Smoke Tests
# ============================================================================

start_agent_background() {
    log_info "Starting agent in background..."

    # shellcheck disable=SC1091
    source "${AGENT_DIR}/.venv/bin/activate"

    cd "${AGENT_DIR}"
    nohup uvicorn agent_app:app --host 0.0.0.0 --port 9001 > /tmp/agent-startup.log 2>&1 &
    local agent_pid=$!
    echo "$agent_pid" > /tmp/agent-install-test.pid

    log_info "Agent PID: ${agent_pid}"
    log_info "Waiting for agent to start..."
    sleep 5 # Give it more time to start (increased from 3)
}

stop_agent_background() {
    if [[ -f /tmp/agent-install-test.pid ]]; then
        local pid
        pid=$(cat /tmp/agent-install-test.pid)
        if kill -0 "$pid" 2>/dev/null; then
            log_info "Stopping test agent (PID ${pid})..."
            kill "$pid" 2>/dev/null || true
            sleep 1
        fi
        rm -f /tmp/agent-install-test.pid
    fi
}

test_health_endpoint() {
    log_info "Testing /health endpoint..."

    local response
    response=$(run_with_timeout 5 curl -s http://localhost:9001/health || echo "FAILED")

    if [[ "$response" == *"ok"* ]]; then
        log_success "/health endpoint is responding"
        return 0
    else
        log_error "/health endpoint failed: ${response}"
        return 1
    fi
}

test_capabilities_endpoint() {
    log_info "Testing /capabilities endpoint..."

    local response
    response=$(run_with_timeout 5 curl -s http://localhost:9001/capabilities || echo "FAILED")

    if [[ "$response" == *"machine_id"* ]]; then
        log_success "/capabilities endpoint is responding"
        echo "$response" | python3 -m json.tool 2>/dev/null || echo "$response"
        return 0
    else
        log_error "/capabilities endpoint failed: ${response}"
        return 1
    fi
}

test_ollama_reachable() {
    log_info "Testing Ollama connectivity (optional)..."

    local response
    response=$(run_with_timeout 5 curl -s http://localhost:11434/api/tags || echo "FAILED")

    if [[ "$response" == *"models"* ]]; then
        log_success "Ollama is reachable at http://localhost:11434"
        return 0
    else
        log_warning "Ollama not reachable (optional, can configure later)"
        return 1
    fi
}

test_comfyui_reachable() {
    log_info "Testing ComfyUI connectivity (optional)..."

    local response
    response=$(run_with_timeout 5 curl -s http://localhost:8188/ || echo "FAILED")

    if [[ "$response" == *"ComfyUI"* ]] || [[ "$response" != "FAILED" ]]; then
        log_success "ComfyUI is reachable at http://localhost:8188"
        return 0
    else
        log_warning "ComfyUI not reachable (optional, can configure later)"
        return 1
    fi
}

run_smoke_tests() {
    log_info "Running smoke tests..."

    local tests_passed=0
    local tests_failed=0

    start_agent_background

    if test_health_endpoint; then
        ((tests_passed++))
    else
        ((tests_failed++))
    fi

    if test_capabilities_endpoint; then
        ((tests_passed++))
    else
        ((tests_failed++))
    fi

    # Optional tests (don't count as failures)
    test_ollama_reachable || true
    test_comfyui_reachable || true

    stop_agent_background

    echo ""
    if [[ $tests_failed -eq 0 ]]; then
        log_success "All smoke tests passed! (${tests_passed}/${tests_passed})"
        return 0
    else
        log_error "Some smoke tests failed (${tests_passed}/$((tests_passed + tests_failed)) passed)"
        return 1
    fi
}

# ============================================================================
# Main Installation Flow
# ============================================================================

main() {
    local agent_id=""
    local label=""
    local central_url=""

    # Parse command-line arguments
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --agent-id)
                agent_id="$2"
                shift 2
                ;;
            --label)
                label="$2"
                shift 2
                ;;
            --central-url)
                central_url="$2"
                shift 2
                ;;
            *)
                log_error "Unknown argument: $1"
                echo "Usage: $0 [--agent-id ID] [--label \"Label\"] [--central-url URL]"
                exit 1
                ;;
        esac
    done

    log_info "==================================================="
    log_info "bench-race Agent Installer (Linux)"
    log_info "==================================================="
    echo ""

    # Detect system specs
    log_info "Detecting system specifications..."
    local hostname
    hostname=$(detect_hostname)
    local cpu_cores
    cpu_cores=$(detect_cpu_cores)
    local cpu_name
    cpu_name=$(detect_cpu_name)
    local ram_gb
    ram_gb=$(detect_ram_gb)
    local gpu_info
    gpu_info=$(detect_gpu_info)

    echo ""
    log_info "Detected system:"
    log_info "  Hostname: ${hostname}"
    log_info "  CPU: ${cpu_name} (${cpu_cores} cores)"
    log_info "  RAM: ${ram_gb}GB"
    log_info "  GPU: ${gpu_info}"
    echo ""

    # Generate default values
    local default_agent_id
    default_agent_id=$(sanitize_id "$hostname")
    local default_label="${hostname} (${cpu_cores} cores, ${ram_gb}GB RAM)"

    # Prompt for user input (if not provided via CLI)
    if [[ -z "$agent_id" ]]; then
        agent_id=$(prompt_for_agent_id "$default_agent_id")
    fi

    if [[ -z "$label" ]]; then
        label=$(prompt_for_label "$default_label")
    fi

    if [[ -z "$central_url" ]]; then
        central_url=$(prompt_for_central_url)
    fi

    echo ""
    log_info "Configuration summary:"
    log_info "  Machine ID: ${agent_id}"
    log_info "  Label: ${label}"
    log_info "  Central URL: ${central_url}"
    echo ""

    # Create config directory if needed
    mkdir -p "$CONFIG_DIR"

    # Generate agent.yaml
    generate_agent_yaml "$agent_id" "$label" "$central_url"

    # Setup Python environment
    setup_python_venv || {
        log_error "Failed to setup Python environment"
        exit 1
    }

    # Run smoke tests
    echo ""
    run_smoke_tests || {
        log_warning "Smoke tests failed, but installation may still be usable"
        log_info "Check logs at /tmp/agent-startup.log"
    }

    echo ""
    log_success "==================================================="
    log_success "Agent installation complete!"
    log_success "==================================================="
    echo ""
    log_info "Next steps:"
    log_info "  1. Start the agent: ./bin/control agent start"
    log_info "  2. Check status: ./bin/control agent status"
    log_info "  3. Add this machine to central/config/machines.yaml:"
    echo ""
    echo "    - machine_id: \"${agent_id}\""
    echo "      label: \"${label}\""
    echo "      agent_base_url: \"http://<this-machine-ip>:9001\""
    echo ""
}

# Run main function
main "$@"
